### PR TITLE
Added pools list

### PR DESCRIPTION
**Pull request by Barbatos**
Hey,

I added the list of the pools. At first they are hidden and when clicking on a "View the Pools" button they all appear.

Do you want the pools' logos to be stored locally?

### CODE REVIEW

**Comment by btcdrak** [comment]
Looks great!

**Comment by btcdrak** [comment]
I would like the logo stored in `images/pools` or something like that.

**Comment by Barbatos** [comment]
I'm on it!

**Comment by Barbatos** [comment]
Done!

**Pull request merged**
